version: "3"
services:
  redis:
    image: redis:latest
    container_name: sam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sam-network
    restart: always
    command: redis-server --appendonly yes

  postgres:
    image: postgres:14
    container_name: sam-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=samdb
      - POSTGRES_USER=samuser
      - POSTGRES_PASSWORD=sampassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sam-network
    restart: always

networks:
  sam-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: