server:
  port: 8090

spring:
  application:
    name: opensam
  datasource:
    url: jdbc:h2:mem:samtest
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
    open-in-view: false