server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: opensam-member
  datasource:
    url: jdbc:h2:mem:samtest
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 180000
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true