server:
  port: 8081

spring:
  application:
    name: opensam-cron
  datasource:
    url: jdbc:h2:mem:testsamdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false